---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 3389, host: 3389}]
  - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[fourthcoffee::default]
    attributes:
